### PR TITLE
Testing Spotlight Elements to display OAS v3

### PR DESCRIPTION
**Pull request by damianpm**
Fixes https://github.com/3scale-labs/kamrad/issues/6

## Testing [Spotlight Elements](https://github.com/stoplightio/elements)

It comes in 2 flavors:

## html

**Pros:**

- It's easy to use, from CDN.
- "Send Request" feature (buggy)

**Cons:**

- Small community
- Includes "Powered by Spotlight" backlink
- Most advanced features require subscription

## React (not working with React 17)

**Pros:**

- None (package is broken)

**Cons:**

- React package is broken, doesn't work with React 17 (see [issue](https://github.com/stoplightio/elements/issues/1447))

**Issues found (React version):**

Trying to install:

```
npm install @stoplight/elements@beta   
```

It fails with error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.8" from @stoplight/elements@7.0.0-beta.6
npm ERR!   node_modules/@stoplight/elements
npm ERR!     @stoplight/elements@"7.0.0-beta.6" from the root project
npm ERR!   77 more (@fortawesome/react-fontawesome, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-simple-code-editor@0.11.0
npm ERR! node_modules/@stoplight/mosaic-code-editor/node_modules/react-simple-code-editor
npm ERR!   react-simple-code-editor@"^0.11.0" from @stoplight/mosaic-code-editor@1.0.0-beta.58
npm ERR!   node_modules/@stoplight/mosaic-code-editor
npm ERR!     @stoplight/mosaic-code-editor@"1.0.0-beta.58" from @stoplight/elements-core@7.0.0-beta.9
npm ERR!     node_modules/@stoplight/elements-core
npm ERR!       @stoplight/elements-core@"7.0.0-beta.9" from @stoplight/elements@7.0.0-beta.6
npm ERR!       node_modules/@stoplight/elements
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/damian/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/damian/.npm/_logs/2021-06-18T15_45_50_346Z-debug.log
```

## How to test

```
hugo server
```

- Go to: http://localhost:1313/posts/oas-spotlight-elements/

This example uses the [Pet Store Spec](https://petstore3.swagger.io/api/v3/openapi.json), but the Send Request feature fails. 

The servers in the spec are:

```
"servers": [
    {
      "url": "/api/v3"
    }
  ],
```

It replaces the server with the local server:

```
http://localhost:1313/api/v3
```

Oas-Spotlight-Elements

- Go to: http://localhost:1313/posts/oas-spotlight-elements-2/

This example uses [another spec](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/uspto.json), with servers:

```
"servers": [
    {
      "url": "{scheme}://developer.uspto.gov/ds-api",
      "variables": {
        "scheme": {
          "description": "The Data Set API is accessible via https and http",
          "enum": [
            "https",
            "http"
          ],
          "default": "https"
        }
      }
    }
  ],
```
In this case, "Send Request" doesn't fails

Oas-Spotlight-Elements-2

## Related PR's:

[Testing Swagger-ui](https://github.com/3scale-labs/kamrad/pull/10)
[Testing Redoc](https://github.com/3scale-labs/kamrad/pull/11)

### CODE REVIEW

**Comment by didierofrivia** [comment]
Too bad about the bug, they'll probably fix it soon. They've also told us about a workaround that is downgrading to npm 6 or using yarn.

**Comment by didierofrivia** [comment]
Screenshot 2021-06-29 at 14 46 21

That's how it's rendered. Is it the same for you?

**Comment by damianpm** [comment]
@didierofrivia 
I was able to use the react flavor:

- Using yarn (to avoid the issue with npm)
- Using webpack instead of ESBuild
- We need to install several packages to satisfy all required dependencies

Check [this commit](https://github.com/3scale-labs/kamrad/pull/12/commits/0af07675b25fde6c04e3fa5ee01cf548407f462f).

To test:

```
rm -rf node_modules && yarn install
```

```
yarn start
```

**Comment by damianpm** [comment]
> Screenshot 2021-06-29 at 14 46 21
> 
> That's how it's rendered. Is it the same for you?

That's because of a conflict with css, between spotlight and the hugo theme.
Using the "stacked" layout of spotlight works fine.

**Comment by damianpm** [comment]
Closed in favor of https://github.com/3scale-labs/kamrad/pull/10

**Pull request closed without merging**
